### Exercise 1

Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.   
Expected Output:

```
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
```

In [ ]:
import numpy as np

In [ ]:
array = np.arange(2, 11)
matriz = array.reshape(3, 3)

print(matriz)



### Exercise 2

Write a NumPy program to create a new array of 3*5, filled with 2.   

Expected Output:

```
array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])
```


In [ ]:
# Create a 3x5 array filled with 2
array = np.full((3, 5), 2)

print("3x5 array filled with 2:")
print(array)

### Exercise 3

Write a NumPy program to create a 5x5 matrix with row values ranging from 0 to 4.  
Expected output:
```
array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])
```

In [ ]:

# Create a 5x5 matrix with row values ranging from 0 to 4
# Method 1: Using np.tile() to repeat the row pattern
row = np.arange(5)
matrix = np.tile(row, (5, 1))

print("5x5 matrix with row values 0 to 4:")
print(matrix)

### Exercise 4
Write a NumPy program to reverse an array (first element becomes last).  

* Original array:  [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]  
* Reverse array:  [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [ ]:

# Original array
original_array = np.array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 
                           25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])

# Reverse the array using slicing
reversed_array = original_array[::-1]

# Display results
print("Original array: ")
print(original_array)
print("\nReverse array: ")
print(reversed_array)

### Exercise 5
Write a NumPy program to create a 1D array containing 20 random integers between 1 and 6 (included).  
Next filter this array to a new one containing only the odd numbers.

In [ ]:
# Create a 1D array with 20 random integers between 1 and 6 (inclusive)
random_array = np.random.randint(1, 7, 20)

# Filter to keep only odd numbers
odd_numbers = random_array[random_array % 2 == 1]

# Display results
print("Original array (20 random integers 1-6):")
print(random_array)
print("\nOdd numbers only:")
print(odd_numbers)

### Exercise 6
Write a NumPy program to get the positions where elements of a and b match  

Input:  
```
a = np.array([1,2,3,2,3,4,3,4,5,6])  
b = np.array([7,2,10,2,7,4,9,4,9,8])  
```

Expected Output:  
```
(array([1, 3, 5, 7]),)
```

In [ ]:

# Input arrays
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Find positions where elements match
matching_positions = np.where(a == b)

print("Positions where elements match:")
print(matching_positions)

### Exercise 7
 Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.   
Checkerboard pattern:  
```
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
 ```

In [ ]:
# Create an 8x8 matrix filled with zeros
checkerboard = np.zeros((8, 8), dtype=int)

# Fill with checkerboard pattern
for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 1:
            checkerboard[i, j] = 1

print("Checkerboard pattern:")
print(checkerboard)

### Exercise 8
 Write a NumPy program to create a 4x4 matrix.  
 Original array:

```
[[ 0 1 2 3]
[ 4 5 6 7]
[ 8 9 10 11]
[12 13 14 15]]  
```

* Extract all the elements of the first and fourth rows.  
Expected output:

```
[[ 0,  1,  2,  3], [12, 13, 14, 15]]
```

* Extract all the elements of the first and fourth columns.  
Expected output :

```
[[ 0 3]
[ 4 7]
[ 8 11]
[12 15]]
```

* Extract second and third elements of the second and third rows  
Expected output:

```
[[ 5 6]
[ 9 10]]
```

In [ ]:
# Create the original 4x4 matrix
original_array = np.array([[0, 1, 2, 3],
                           [4, 5, 6, 7],
                           [8, 9, 10, 11],
                           [12, 13, 14, 15]])

print("Original array:")
print(original_array)

# 1. Extract first and fourth rows
rows_1_and_4 = original_array[[0, 3], :]
print("\nFirst and fourth rows:")
print(rows_1_and_4)

# 2. Extract first and fourth columns
cols_1_and_4 = original_array[:, [0, 3]]
print("\nFirst and fourth columns:")
print(cols_1_and_4)

# 3. Extract second and third elements of second and third rows
# Second and third rows: indices 1 and 2
# Second and third elements: indices 1 and 2
subset = original_array[1:3, 1:3]
print("\nSecond and third elements of second and third rows:")
print(subset)

### Exercise 9
Import a dataset with numbers and texts _keeping the text intact_ in a python NumPy array.

The dataset can be found on this url: [https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data).  

The data is also available as iris.csv in the files folder.

Each row consists of 5 fields:
* 'sepallength': number
* 'sepalwidth': number
* 'petallength': number
* 'petalwidth': number
* 'species': text

To load this dataset you need to use the genfromtxt() function and make sure that dtype is set to object. Otherwise the 'species' field will contain NaN values.  

Expected output (first 3 rows)
```
array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)
```

In [ ]:

iris_data = np.genfromtxt('files/iris.csv', delimiter=',', dtype=object, encoding=None, skip_header=0)

# Display the first 3 rows as expected
print(iris_data[:3])

### Exercise 10
Import the iris dataset again but now just the first four columns.  
Check if there are any missing values in the sepallength (1st column).  
This can be done with the function isnan()  

Expected output:  
Number of missing values: 0  
Position of missing values:
```
(array([], dtype=int64),)
```

Use the commented code in the first block to introduce some missing values. This will help you make sure your code works.

In [ ]:
# initialisation
#url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
#iris_numbers = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

## If the URL doesn't work
iris_numbers = np.genfromtxt('files/iris.csv', delimiter=',', dtype=float, encoding=None, skip_header=1,usecols=[0,1,2,3])

iris_numbers[1,2] = np.nan
iris_numbers[2,2] = np.nan

In [ ]:

sepallength = iris_numbers[:, 0]

# Check for missing values using isnan()
missing_values = np.isnan(sepallength)

# Count missing values
num_missing = np.sum(missing_values)

# Find positions of missing values
positions = np.where(missing_values)

# Display results
print("Number of missing values:", num_missing)
print("Position of missing values:")
print(positions)

### Exercise 11
Compute the mean, median, standard deviation of iris's sepallength (1st column)  

Expected output:  
```
mean: 5.843333333333334   
median: 5.8   
standard deviation: 0.8253012917851409  
```

In [ ]:
iris_numbers = np.genfromtxt('files/iris.csv', delimiter=',', dtype=float, 
                              encoding=None, skip_header=1, usecols=[0,1,2,3])

# Extract the first column (sepallength)
sepallength = iris_numbers[:, 0]

# Compute statistics
mean_value = np.mean(sepallength)
median_value = np.median(sepallength)
std_value = np.std(sepallength)

# Display results
print("mean:", mean_value)
print("median:", median_value)
print("standard deviation:", std_value)

### Exercise 12
Find the 5th and 95th percentile of iris's sepallength.  (1st column)  

Expected output:
```
array([4.6  , 7.255])
```

In [ ]:

# Load the Iris dataset (first 4 columns)
iris_numbers = np.genfromtxt('files/iris.csv', delimiter=',', dtype=float, 
                              encoding=None, skip_header=1, usecols=[0,1,2,3])

# Extract the first column (sepallength)
sepallength = iris_numbers[:, 0]

# Compute the 5th and 95th percentiles
percentiles = np.percentile(sepallength, [5, 95])

# Display results
print(percentiles)

### Exercise 13
Filter the rows in the iris data array that haves petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0  
The resulting array contains the 4 numeric fields for each retrieved row.  

Expected output: 
``` 
array([[4.8, 3.4, 1.6, 0.2],  
       [4.8, 3.4, 1.9, 0.2],  
       [4.7, 3.2, 1.6, 0.2],  
       [4.8, 3.1, 1.6, 0.2],  
       [4.9, 2.4, 3.3, 1. ],  
       [4.9, 2.5, 4.5, 1.7]])
```


In [ ]:

# Load the Iris dataset (first 4 columns)
iris_numbers = np.genfromtxt('files/iris.csv', delimiter=',', dtype=float, 
                              encoding=None, skip_header=1, usecols=[0,1,2,3])

# Filter rows based on conditions:
# - petallength (3rd column, index 2) > 1.5
# - sepallength (1st column, index 0) < 5.0
filtered_rows = iris_numbers[(iris_numbers[:, 2] > 1.5) & (iris_numbers[:, 0] < 5.0)]

# Display the filtered array
print(filtered_rows)